name: main

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up bazelisk
      uses: bazelbuild/setup-bazelisk@v2

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel

    - name: Build
      run: bazel build //...

    - name: Test
      run: bazel test //...
